apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        nodePort: 30080
      websecure:
        nodePort: 30443
    certificatesResolvers:
      letsencrypt:
        acme:
          email: nnkitsaini@gmail.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=nnkitsaini@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
