# This file has been generated by node2nix 1.11.1. Do not edit!

# NOTE: Just to get latest version of svelte-language-server
# Generated by running `node2nix -i node-packages.json`, 
# `node-package.json` just contains `["svelte-language-server"]`

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ampproject/remapping-2.3.0" = {
      name = "_at_ampproject_slash_remapping";
      packageName = "@ampproject/remapping";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.3.0.tgz";
        sha512 = "30iZtAPgz+LTIYoeivqYo853f02jBYSd5uGnGpkFV0M3xOt9aN73erkgYAmZU43x4VfqcnLxW9Kpg3R5LC4YYw==";
      };
    };
    "@babel/code-frame-7.24.2" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.24.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.24.2.tgz";
        sha512 = "y5+tLQyV8pg3fsiln67BVLD1P13Eg4lh5RW9mF0zUuvLrv9uIQ4MCL+CRT+FTsBlBjcIan6PGsLcBN0m3ClUyQ==";
      };
    };
    "@babel/compat-data-7.24.4" = {
      name = "_at_babel_slash_compat-data";
      packageName = "@babel/compat-data";
      version = "7.24.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/compat-data/-/compat-data-7.24.4.tgz";
        sha512 = "vg8Gih2MLK+kOkHJp4gBEIkyaIi00jgWot2D9QOmmfLC8jINSOzmCLta6Bvz/JSBCqnegV0L80jhxkol5GWNfQ==";
      };
    };
    "@babel/core-7.24.4" = {
      name = "_at_babel_slash_core";
      packageName = "@babel/core";
      version = "7.24.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/core/-/core-7.24.4.tgz";
        sha512 = "MBVlMXP+kkl5394RBLSxxk/iLTeVGuXTV3cIDXavPpMMqnSnt6apKgan/U8O3USWZCWZT/TbgfEpKa4uMgN4Dg==";
      };
    };
    "@babel/generator-7.24.4" = {
      name = "_at_babel_slash_generator";
      packageName = "@babel/generator";
      version = "7.24.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/generator/-/generator-7.24.4.tgz";
        sha512 = "Xd6+v6SnjWVx/nus+y0l1sxMOTOMBkyL4+BIdbALyatQnAe/SRVjANeDPSCYaX+i1iJmuGSKf3Z+E+V/va1Hvw==";
      };
    };
    "@babel/helper-compilation-targets-7.23.6" = {
      name = "_at_babel_slash_helper-compilation-targets";
      packageName = "@babel/helper-compilation-targets";
      version = "7.23.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-compilation-targets/-/helper-compilation-targets-7.23.6.tgz";
        sha512 = "9JB548GZoQVmzrFgp8o7KxdgkTGm6xs9DW0o/Pim72UDjzr5ObUQ6ZzYPqA+g9OTS2bBQoctLJrky0RDCAWRgQ==";
      };
    };
    "@babel/helper-environment-visitor-7.22.20" = {
      name = "_at_babel_slash_helper-environment-visitor";
      packageName = "@babel/helper-environment-visitor";
      version = "7.22.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-environment-visitor/-/helper-environment-visitor-7.22.20.tgz";
        sha512 = "zfedSIzFhat/gFhWfHtgWvlec0nqB9YEIVrpuwjruLlXfUSnA8cJB0miHKwqDnQ7d32aKo2xt88/xZptwxbfhA==";
      };
    };
    "@babel/helper-function-name-7.23.0" = {
      name = "_at_babel_slash_helper-function-name";
      packageName = "@babel/helper-function-name";
      version = "7.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-function-name/-/helper-function-name-7.23.0.tgz";
        sha512 = "OErEqsrxjZTJciZ4Oo+eoZqeW9UIiOcuYKRJA4ZAgV9myA+pOXhhmpfNCKjEH/auVfEYVFJ6y1Tc4r0eIApqiw==";
      };
    };
    "@babel/helper-hoist-variables-7.22.5" = {
      name = "_at_babel_slash_helper-hoist-variables";
      packageName = "@babel/helper-hoist-variables";
      version = "7.22.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-hoist-variables/-/helper-hoist-variables-7.22.5.tgz";
        sha512 = "wGjk9QZVzvknA6yKIUURb8zY3grXCcOZt+/7Wcy8O2uctxhplmUPkOdlgoNhmdVee2c92JXbf1xpMtVNbfoxRw==";
      };
    };
    "@babel/helper-module-imports-7.24.3" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.24.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.24.3.tgz";
        sha512 = "viKb0F9f2s0BCS22QSF308z/+1YWKV/76mwt61NBzS5izMzDPwdq1pTrzf+Li3npBWX9KdQbkeCt1jSAM7lZqg==";
      };
    };
    "@babel/helper-module-transforms-7.23.3" = {
      name = "_at_babel_slash_helper-module-transforms";
      packageName = "@babel/helper-module-transforms";
      version = "7.23.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-transforms/-/helper-module-transforms-7.23.3.tgz";
        sha512 = "7bBs4ED9OmswdfDzpz4MpWgSrV7FXlc3zIagvLFjS5H+Mk7Snr21vQ6QwrsoCGMfNC4e4LQPdoULEt4ykz0SRQ==";
      };
    };
    "@babel/helper-simple-access-7.22.5" = {
      name = "_at_babel_slash_helper-simple-access";
      packageName = "@babel/helper-simple-access";
      version = "7.22.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-simple-access/-/helper-simple-access-7.22.5.tgz";
        sha512 = "n0H99E/K+Bika3++WNL17POvo4rKWZ7lZEp1Q+fStVbUi8nxPQEBOlTmCOxW/0JsS56SKKQ+ojAe2pHKJHN35w==";
      };
    };
    "@babel/helper-split-export-declaration-7.22.6" = {
      name = "_at_babel_slash_helper-split-export-declaration";
      packageName = "@babel/helper-split-export-declaration";
      version = "7.22.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-split-export-declaration/-/helper-split-export-declaration-7.22.6.tgz";
        sha512 = "AsUnxuLhRYsisFiaJwvp1QF+I3KjD5FOxut14q/GzovUe6orHLesW2C7d754kRm53h5gqrz6sFl6sxc4BVtE/g==";
      };
    };
    "@babel/helper-string-parser-7.24.1" = {
      name = "_at_babel_slash_helper-string-parser";
      packageName = "@babel/helper-string-parser";
      version = "7.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.24.1.tgz";
        sha512 = "2ofRCjnnA9y+wk8b9IAREroeUP02KHp431N2mhKniy2yKIDKpbrHv9eXwm8cBeWQYcJmzv5qKCu65P47eCF7CQ==";
      };
    };
    "@babel/helper-validator-identifier-7.22.20" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.22.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.22.20.tgz";
        sha512 = "Y4OZ+ytlatR8AI+8KZfKuL5urKp7qey08ha31L8b3BwewJAoJamTzyvxPR/5D+KkdJCGPq/+8TukHBlY10FX9A==";
      };
    };
    "@babel/helper-validator-option-7.23.5" = {
      name = "_at_babel_slash_helper-validator-option";
      packageName = "@babel/helper-validator-option";
      version = "7.23.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-option/-/helper-validator-option-7.23.5.tgz";
        sha512 = "85ttAOMLsr53VgXkTbkx8oA6YTfT4q7/HzXSLEYmjcSTJPMPQtvq1BD79Byep5xMUYbGRzEpDsjUf3dyp54IKw==";
      };
    };
    "@babel/helpers-7.24.4" = {
      name = "_at_babel_slash_helpers";
      packageName = "@babel/helpers";
      version = "7.24.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helpers/-/helpers-7.24.4.tgz";
        sha512 = "FewdlZbSiwaVGlgT1DPANDuCHaDMiOo+D/IDYRFYjHOuv66xMSJ7fQwwODwRNAPkADIO/z1EoF/l2BCWlWABDw==";
      };
    };
    "@babel/highlight-7.24.2" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.24.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.24.2.tgz";
        sha512 = "Yac1ao4flkTxTteCDZLEvdxg2fZfz1v8M4QpaGypq/WPDqg3ijHYbDfs+LG5hvzSoqaSZ9/Z9lKSP3CjZjv+pA==";
      };
    };
    "@babel/parser-7.24.4" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.24.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.24.4.tgz";
        sha512 = "zTvEBcghmeBma9QIGunWevvBAp4/Qu9Bdq+2k0Ot4fVMD6v3dsC9WOcRSKk7tRRyBM/53yKMJko9xOatGQAwSg==";
      };
    };
    "@babel/template-7.24.0" = {
      name = "_at_babel_slash_template";
      packageName = "@babel/template";
      version = "7.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/template/-/template-7.24.0.tgz";
        sha512 = "Bkf2q8lMB0AFpX0NFEqSbx1OkTHf0f+0j82mkw+ZpzBnkk7e9Ql0891vlfgi+kHwOk8tQjiQHpqh4LaSa0fKEA==";
      };
    };
    "@babel/traverse-7.24.1" = {
      name = "_at_babel_slash_traverse";
      packageName = "@babel/traverse";
      version = "7.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/traverse/-/traverse-7.24.1.tgz";
        sha512 = "xuU6o9m68KeqZbQuDt2TcKSxUw/mrsvavlEqQ1leZ/B+C9tk6E4sRWy97WaXgvq5E+nU3cXMxv3WKOCanVMCmQ==";
      };
    };
    "@babel/types-7.24.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.24.0.tgz";
        sha512 = "+j7a5c253RfKh8iABBhywc8NSfP5LURe7Uh4qpsh6jc+aLJguvmIUBdjSdEMQv2bENrCR5MfRdjGo7vzS/ob7w==";
      };
    };
    "@emmetio/abbreviation-2.3.3" = {
      name = "_at_emmetio_slash_abbreviation";
      packageName = "@emmetio/abbreviation";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.3.3.tgz";
        sha512 = "mgv58UrU3rh4YgbE/TzgLQwJ3pFsHHhCLqY20aJq+9comytTXUDNGG/SMtSeMJdkpxgXSXunBGLD8Boka3JyVA==";
      };
    };
    "@emmetio/css-abbreviation-2.1.8" = {
      name = "_at_emmetio_slash_css-abbreviation";
      packageName = "@emmetio/css-abbreviation";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.8.tgz";
        sha512 = "s9yjhJ6saOO/uk1V74eifykk2CBYi01STTK3WlXWGOepyKa23ymJ053+DNQjpFcy1ingpaO7AxCcwLvHFY9tuw==";
      };
    };
    "@emmetio/scanner-1.0.4" = {
      name = "_at_emmetio_slash_scanner";
      packageName = "@emmetio/scanner";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.4.tgz";
        sha512 = "IqRuJtQff7YHHBk4G8YZ45uB9BaAGcwQeVzgj/zj8/UdOhtQpEIupUhSk8dys6spFIWVZVeK20CzGEnqR5SbqA==";
      };
    };
    "@jridgewell/gen-mapping-0.3.5" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.5.tgz";
        sha512 = "IzL8ZoEDIBRWEzlCcRhOaCupYyN5gdIK+Q6fbFdPDg6HqX6jpkItn7DFIpW9LQzXG6Df9sA7+OKnq0qlz/GaQg==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/set-array-1.2.1" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.2.1.tgz";
        sha512 = "R8gLRTZeyp03ymzP/6Lil/28tGeGEzhx1q2k703KGWRAI1VdvPIXdG70VJc2pAMw3NA6JKL5hhFu1sJX0Mnn/A==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.15" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.15.tgz";
        sha512 = "eF2rxCRulEKXHTRiDrDy6erMYWqNw4LPdQ8UQA4huuxaQsVeRPFl2oM8oDGxMFhJUWZf9McpLtJasDDZb/Bpeg==";
      };
    };
    "@jridgewell/trace-mapping-0.3.25" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.25.tgz";
        sha512 = "vNk6aEwybGtawWmy/PzwnGDOjCkLWSD2wqvjGGAgOAwCGWySYXfYoxt00IJkTF+8Lb57DwOb3Aa0o9CApepiYQ==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@types/pug-2.0.10" = {
      name = "_at_types_slash_pug";
      packageName = "@types/pug";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pug/-/pug-2.0.10.tgz";
        sha512 = "Sk/uYFOBAB7mb74XcpizmH0KOR2Pv3D2Hmrh1Dmy5BmK3MpdSa5kqZcg6EKBdklU0bFXX9gCfzvpnyUehrPIuA==";
      };
    };
    "@vscode/emmet-helper-2.8.4" = {
      name = "_at_vscode_slash_emmet-helper";
      packageName = "@vscode/emmet-helper";
      version = "2.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.8.4.tgz";
        sha512 = "lUki5QLS47bz/U8IlG9VQ+1lfxMtxMZENmU5nu4Z71eOD5j9FK0SmYGL5NiVJg9WBWeAU0VxRADMY2Qpq7BfVg==";
      };
    };
    "@vscode/l10n-0.0.18" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.18.tgz";
        sha512 = "KYSIHVmslkaCDyw013pphY+d7x1qV8IZupYfeIfzNA+nsaWHbn5uPuQRvdRFsa9zFzGeudPuoGoZ1Op4jrJXIQ==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "anymatch-3.1.3" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
        sha512 = "KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha512 = "BSHWgDSAiKs50o2Re8ppvp3seVHXSRM44cdSsT9FfNEUUZLOGWVCsiWaRPWM1Znn+mqZ1OfVZ3z3DWEzSp7hRA==";
      };
    };
    "assert-never-1.2.1" = {
      name = "assert-never";
      packageName = "assert-never";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-never/-/assert-never-1.2.1.tgz";
        sha512 = "TaTivMB6pYI1kXwrFlEhLeGfOqoDNdTxjCdwRfFFkEA30Eu+k48W34nlok2EYWJfFFzqaEmichdNM7th6M5HNw==";
      };
    };
    "atob-2.1.2" = {
      name = "atob";
      packageName = "atob";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.1.2.tgz";
        sha512 = "Wm6ukoaOGJi/73p/cl2GvLjTI5JM1k/O14isD73YML8StrH/7/lRFgmg8nICZgD3bZZvjwCGxtMOD3wWNAu8cg==";
      };
    };
    "babel-walk-3.0.0-canary-5" = {
      name = "babel-walk";
      packageName = "babel-walk";
      version = "3.0.0-canary-5";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-walk/-/babel-walk-3.0.0-canary-5.tgz";
        sha512 = "GAwkz0AihzY5bkwIY5QDR+LvsRQgB/B+1foMPvi0FZPMl5fjD7ICiznUiBdLYMH1QYe6vqu4gWYytZOccLouFw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "binary-extensions-2.3.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.3.0.tgz";
        sha512 = "Ceh+7ox5qe7LJuLHoY0feh3pHuUDHAcRUeyL2VYghZwfpkNIy/+8Ocg0a3UuSoYzavmylwuLWQOf3hl0jjMMIw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "browserslist-4.23.0" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.23.0.tgz";
        sha512 = "QW8HiM1shhT2GuzkvklfjcKDiWFXHOeFCIA/huJPwHsslwcydgk7X+z2zXpEijP98UCY7HbubZt5J2Zgvf0CaQ==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha512 = "VO9Ht/+p3SN7SKWqcrgEzjGbRSJYTx+Q1pTQC0wrWqHx0vpJraQ6GtHx8tvcg1rlK1byhU5gccxgOgj7B0TDkQ==";
      };
    };
    "call-bind-1.0.7" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.7.tgz";
        sha512 = "GHTSNSYICQ7scH7sZ+M2rFopRoLh8t2bLSW6BbgrtLsahOIB5iyAVJf9GjWK3cYTDaMj4XdBpM1cA6pIS0Kv2w==";
      };
    };
    "caniuse-lite-1.0.30001613" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001613";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001613.tgz";
        sha512 = "BNjJULJfOONQERivfxte7alLfeLW4QnwHvNW4wEcLEbXfV6VSCYvr+REbf2Sojv8tC1THpjPXBxWgDbq4NtLWg==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "chokidar-3.6.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.6.0.tgz";
        sha512 = "7VT13fmjotKpGipCW9JEQAusEPE+Ei8nl6/g4FBAmIm0GOOLMua9NDDo/DWp0ZAxCr3cPq5ZpBqmPAQgDda2Pw==";
      };
    };
    "coffeescript-2.7.0" = {
      name = "coffeescript";
      packageName = "coffeescript";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffeescript/-/coffeescript-2.7.0.tgz";
        sha512 = "hzWp6TUE2d/jCcN67LrW1eh5b/rSDKQK6oD6VMLlggYVUUFexgTH9z3dNYihzX4RMhze5FTUsUmOXViJKFQR/A==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "constantinople-4.0.1" = {
      name = "constantinople";
      packageName = "constantinople";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/constantinople/-/constantinople-4.0.1.tgz";
        sha512 = "vCrqcSIq4//Gx74TXXCGnHpulY1dskqLTFGDmhrGxzeXL8lF8kvXv6mpNWlJj1uD4DW23D4ljAqbY4RRaaUZIw==";
      };
    };
    "convert-source-map-2.0.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-2.0.0.tgz";
        sha512 = "Kvp459HrV2FEJ1CAsi1Ku+MY3kasH19TFykTz2xWmMeq6bk2NU3XXvfJ+Q61m0xktWwt+1HSYf3JZsTms3aRJg==";
      };
    };
    "copy-anything-2.0.6" = {
      name = "copy-anything";
      packageName = "copy-anything";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-anything/-/copy-anything-2.0.6.tgz";
        sha512 = "1j20GZTsvKNkc4BY3NpMOM8tt///wY3FpIzozTOFO2ffuZcV61nojHXVKIy3WM+7ADCy5FVhdZYHYDdgTU0yJw==";
      };
    };
    "css-3.0.0" = {
      name = "css";
      packageName = "css";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css/-/css-3.0.0.tgz";
        sha512 = "DG9pFfwOrzc+hawpmqX/dHYHJG+Bsdb0klhyi1sDneOgGOXy9wQIC8hzyVp1e4NRYDBdxcylvywPkkXCHAzTyQ==";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "decode-uri-component-0.2.2" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.2.tgz";
        sha512 = "FqUYQ+8o158GyGTrMFJms9qh3CqTKvAqgqsTnkLI8sKu0028orqBhxNMFkFen0zGyg6epACD32pjVk58ngIErQ==";
      };
    };
    "dedent-js-1.0.1" = {
      name = "dedent-js";
      packageName = "dedent-js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dedent-js/-/dedent-js-1.0.1.tgz";
        sha512 = "OUepMozQULMLUmhxS95Vudo0jb0UchLimi3+pQ2plj61Fcy8axbP9hbiD4Sz6DPqn6XG3kfmziVfQ1rSys5AJQ==";
      };
    };
    "define-data-property-1.1.4" = {
      name = "define-data-property";
      packageName = "define-data-property";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-data-property/-/define-data-property-1.1.4.tgz";
        sha512 = "rBMvIzlpA8v6E+SJZoo++HAYqsLrkg7MSfIinMPFhmkorw7X+dOXVJQs+QT69zGkzMyfDnIMN2Wid1+NbL3T+A==";
      };
    };
    "detect-indent-6.1.0" = {
      name = "detect-indent";
      packageName = "detect-indent";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-indent/-/detect-indent-6.1.0.tgz";
        sha512 = "reYkTUJAZb9gUuZ2RvVCNhVHdg62RHnJ7WJl8ftMi4diZ6NWlciOzQN88pUhSELEwflJht4oQDv0F0BMlwaYtA==";
      };
    };
    "doctypes-1.1.0" = {
      name = "doctypes";
      packageName = "doctypes";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctypes/-/doctypes-1.1.0.tgz";
        sha512 = "LLBi6pEqS6Do3EKQ3J0NqHWV5hhb78Pi8vvESYwyOy2c31ZEZVdtitdzsQsKb7878PEERhzUk0ftqGhG6Mz+pQ==";
      };
    };
    "electron-to-chromium-1.4.750" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.4.750";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.750.tgz";
        sha512 = "9ItEpeu15hW5m8jKdriL+BQrgwDTXEL9pn4SkillWFu73ZNNNQ2BKKLS+ZHv2vC9UkNhosAeyfxOf/5OSeTCPA==";
      };
    };
    "emmet-2.4.7" = {
      name = "emmet";
      packageName = "emmet";
      version = "2.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/emmet/-/emmet-2.4.7.tgz";
        sha512 = "O5O5QNqtdlnQM2bmKHtJgyChcrFMgQuulI+WdiOw2NArzprUqqxUW6bgYtKvzKgrsYpuLWalOkdhNP+1jluhCA==";
      };
    };
    "errno-0.1.8" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.8.tgz";
        sha512 = "dJ6oBr5SQ1VSd9qkk7ByRgb/1SH4JZjCHSW/mr63/QcXO9zLVxvJ6Oy13nio03rxpSnVDDjFor75SjVeZWPW/A==";
      };
    };
    "es-define-property-1.0.0" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.0.tgz";
        sha512 = "jxayLKShrEqqzJ0eumQbVhTYQM27CfT1T35+gCgDFoL82JLsXqTJ76zv6A0YLOgEnLUMvLzsDsGIrl8NFpT2gQ==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es6-promise-3.3.1" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-3.3.1.tgz";
        sha512 = "SOp9Phqvqn7jtEUxPWdWfWoLmyt2VaJ6MpvP9Comy1MceMXqE6bxvaTu4iaxpYYPzhny28Lc+M87/c2cPK6lDg==";
      };
    };
    "escalade-3.1.2" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.2.tgz";
        sha512 = "ErCHMCae19vR8vQGe50xIsVomy19rg6gFu3+r3jkEO46suLMWBksvVyoGgQV+jOfl84ZSOSlmv6Gxa89PmTGmA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "fast-glob-3.3.2" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.3.2.tgz";
        sha512 = "oX2ruAFQwf/Orj8m737Y5adxDQO0LAB7/S5MnxCdTNDd4p6BsyIVsv9JQsATbTSq8KHRpLwIHbVlUNatxd+1Ow==";
      };
    };
    "fastq-1.17.1" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.17.1.tgz";
        sha512 = "sRVD3lWVIXWg6By68ZN7vho9a1pQcN/WBFaAAsDDFzlJjvoGx0P8z7V1t72grFJfJhu3YPZBuu25f7Kaw2jN1w==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "gensync-1.0.0-beta.2" = {
      name = "gensync";
      packageName = "gensync";
      version = "1.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensync/-/gensync-1.0.0-beta.2.tgz";
        sha512 = "3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==";
      };
    };
    "get-intrinsic-1.2.4" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.4.tgz";
        sha512 = "5uYhsJH8VJBTv7oslg4BznJYhDoRI6waYCxMmCdnTrcCrHA/fCFKoTFz2JKKE0HdDFUF7/oQuhzumXJK7paBRQ==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "globals-11.12.0" = {
      name = "globals";
      packageName = "globals";
      version = "11.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-11.12.0.tgz";
        sha512 = "WOBp/EEGUiIsJSp7wcv/y6MO+lV9UoncWqxuFfm8eBwzWNgyfBd6Gz+IeKQ9jCmyhoH99g15M3T+QaVHFjizVA==";
      };
    };
    "gopd-1.0.1" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.0.1.tgz";
        sha512 = "d65bNlIadxvpb/A2abVdlqKqV563juRnZ1Wtk6s1sIR8uNsXR70xqIzVqxVf1eTqDunwT2MkczEeaezCKTZhwA==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "has-property-descriptors-1.0.2" = {
      name = "has-property-descriptors";
      packageName = "has-property-descriptors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-property-descriptors/-/has-property-descriptors-1.0.2.tgz";
        sha512 = "55JNKuIW+vq4Ke1BjOTjM2YctQIvCT7GFzHwmfZPGo5wnrgkid0YQtnAleFSqumZm4az3n2BS+erby5ipJdgrg==";
      };
    };
    "has-proto-1.0.3" = {
      name = "has-proto";
      packageName = "has-proto";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-proto/-/has-proto-1.0.3.tgz";
        sha512 = "SJ1amZAJUiZS+PhsVLf5tGydlaVB8EdFpaSO4gmiUKUOxk8qzn5AIy4ZeJUmh22znIdk/uMAUT2pl3FxzVUH+Q==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "image-size-0.5.5" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz";
        sha512 = "6TDAlDPZxUFCv+fuOkIoXT/V/f3Qbq8e37p+YOiYrUv3v9cc3/6x78VdfPgFVaB9dZYeLUfKgHRebpkm/oP2VQ==";
      };
    };
    "immutable-4.3.5" = {
      name = "immutable";
      packageName = "immutable";
      version = "4.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-4.3.5.tgz";
        sha512 = "8eabxkth9gZatlwl5TBuJnCsoTADlL6ftEr7A4qgdaTsPyreilDSnUk57SO+jfKcNtxPa22U5KK6DSeAYhpBJw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-core-module-2.13.1" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.13.1.tgz";
        sha512 = "hHrIjvZsftOsvKSn2TRYl63zvxsgE0K+0mYMoH6gD4omR5IWB2KynivBQczo3+wF1cCkjzvptnI9Q0sPU66ilw==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-promise-2.2.2" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.2.2.tgz";
        sha512 = "+lP4/6lKUBfQjZ2pdxThZvLUAafmZb8OAxFb8XXtiQmS35INgr85hdOGoEs124ez1FCnZJt6jau/T+alh58QFQ==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "is-what-3.14.1" = {
      name = "is-what";
      packageName = "is-what";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-what/-/is-what-3.14.1.tgz";
        sha512 = "sNxgpk9793nzSs7bA6JQJGeIuRBQhAaNGG77kzYQgMkrID+lS6SlK07K5LaptscDlSaIgH+GPFzf+d75FVxozA==";
      };
    };
    "jiti-1.21.0" = {
      name = "jiti";
      packageName = "jiti";
      version = "1.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-1.21.0.tgz";
        sha512 = "gFqAIbuKyyso/3G2qhiO2OM6shY6EPP/R0+mkDbyspxKazh8BXDC5FiFsUjlczgdNz/vfra0da2y+aHrusLG/Q==";
      };
    };
    "js-stringify-1.0.2" = {
      name = "js-stringify";
      packageName = "js-stringify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-stringify/-/js-stringify-1.0.2.tgz";
        sha512 = "rtS5ATOo2Q5k1G+DADISilDA6lv79zIiwFd6CcjuIxGKLFm5C+RLImRscVap9k55i+MOZwgliw+NejvkLuGD5g==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jsesc-2.5.2" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-2.5.2.tgz";
        sha512 = "OYu7XEzjkCQ3C5Ps3QIZsQfNpqoJyZZA99wd9aWd05NCtC5pWOkShK2mkL6HXQR6/Cy2lbNdPlZBpuQHXE63gA==";
      };
    };
    "json5-2.2.3" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.3.tgz";
        sha512 = "XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8lXGf6zYwDUzeHMWfxasyg==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "jstransformer-1.0.0" = {
      name = "jstransformer";
      packageName = "jstransformer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransformer/-/jstransformer-1.0.0.tgz";
        sha512 = "C9YK3Rf8q6VAPDCCU9fnqo3mAfOH6vUGnMcP4AQAYIEpWtfGLpwOTmZ+igtdK5y+VvI2n3CyYSzy4Qh34eq24A==";
      };
    };
    "less-4.2.0" = {
      name = "less";
      packageName = "less";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-4.2.0.tgz";
        sha512 = "P3b3HJDBtSzsXUl0im2L7gTO5Ubg8mEN6G8qoTS77iXxXX4Hvu4Qj540PZDvQ8V6DmX6iXo98k7Md0Cm1PrLaA==";
      };
    };
    "lilconfig-3.1.1" = {
      name = "lilconfig";
      packageName = "lilconfig";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lilconfig/-/lilconfig-3.1.1.tgz";
        sha512 = "O18pf7nyvHTckunPWCV1XUNXU1piu01y2b7ATJ0ppkUkk8ocqVWBrYjJBCwHDjD/ZWcfyrA0P4gKhzWGi5EINQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lower-case-2.0.2" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-2.0.2.tgz";
        sha512 = "7fm3l3NAF9WfN6W3JOmf5drwpVqX78JtoGJ3A6W0a6ZnldM41w2fV5D490psKFTpMds8TJse/eHLFFsNHHjHgg==";
      };
    };
    "lru-cache-5.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-5.1.1.tgz";
        sha512 = "KpNARQA3Iwv+jTA0utUVVbrh+Jlrr1Fv0e56GGzAFOXN7dk/FviaDW8LHmK52DlcH4WP2n6gI8vN1aesBFgo9w==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "magic-string-0.30.10" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.10.tgz";
        sha512 = "iIRwTIf0QKV3UAnYK4PU8uiEc4SRh5jX0mwpIwETPpHdhVM4f53RSwS/vXvN1JhGX+Cs7B8qIq3d6AH49O5fAQ==";
      };
    };
    "make-dir-2.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-2.1.0.tgz";
        sha512 = "LS9X+dc8KLxXCb8dni79fLIIUA5VyZoyjSMCwTluaXA0o27cCK0bhXkpgw+sTXVpPy/lSO57ilRixqk0vDmtRA==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "micromatch-4.0.5" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.5.tgz";
        sha512 = "DMy+ERcEW2q8Z2Po+WNXuw3c5YaUSFjAO5GsJqfEl7UjvtIuFKO6ZrKvcItdy98dwFI2N1tg3zNIdKaQT+aNdA==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "min-indent-1.0.1" = {
      name = "min-indent";
      packageName = "min-indent";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/min-indent/-/min-indent-1.0.1.tgz";
        sha512 = "I9jwMn07Sy/IwOj3zVkVik2JTvgpaykDZEigL6Rx6N9LbMywwUSMtxET+7lVoDLLd3O3IXwJwvuuns8UB/HeAg==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "mkdirp-0.5.6" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.6.tgz";
        sha512 = "FP+p8RB8OWpF3YZBCrP5gtADmtXApB5AMLn+vdyA+PyxCjrCs00mjyUozssO33cwDeT3wNGdLxJ5M//YqtHAJw==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nanoid-3.3.7" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.7.tgz";
        sha512 = "eSRppjcPIatRIMC1U6UngP8XFcz8MQWGQdt1MTBQ7NaAmvXDfvNxbvWV3x2y6CdEUciCSsDHDQZbhYaB8QEo2g==";
      };
    };
    "needle-3.3.1" = {
      name = "needle";
      packageName = "needle";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/needle/-/needle-3.3.1.tgz";
        sha512 = "6k0YULvhpw+RoLNiQCRKOl09Rv1dPLr8hHnVjHqdolKwDrdNyk+Hmrthi4lIGPPz3r39dLx0hsF5s40sZ3Us4Q==";
      };
    };
    "no-case-3.0.4" = {
      name = "no-case";
      packageName = "no-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-3.0.4.tgz";
        sha512 = "fgAN3jGAh+RoxUGZHTSOLJIqUc2wmoBwGR4tbpNAKmmovFoWq0OdRkb0VkldReO2a2iBT/OEulG9XSUc10r3zg==";
      };
    };
    "node-releases-2.0.14" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.14.tgz";
        sha512 = "y10wOWt8yZpqXmOgRo77WaHEmhYQYGNA6y421PKsKYWEK8aW+cqAphborZDhqfyKrbZEN92CN1X2KbafY2s7Yw==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "parse-node-version-1.0.1" = {
      name = "parse-node-version";
      packageName = "parse-node-version";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-node-version/-/parse-node-version-1.0.1.tgz";
        sha512 = "3YHlOa/JgH6Mnpr05jP9eDG254US9ek25LyIxZlDItp2iJtwyaXQb57lBYLdT3MowkUFYEV2XXNAYIPlESvJlA==";
      };
    };
    "pascal-case-3.1.2" = {
      name = "pascal-case";
      packageName = "pascal-case";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascal-case/-/pascal-case-3.1.2.tgz";
        sha512 = "uWlGT3YSnK9x3BQJaOdcZwrnV6hPpd8jFH1/ucpiLRPh/2zCVJKS19E4GvYHvaCcACn3foXZ0cLB9Wrx1KGe5g==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pify-4.0.1" = {
      name = "pify";
      packageName = "pify";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-4.0.1.tgz";
        sha512 = "uB80kBFb/tfd68bVleG9T5GGsGPjJrLAUpR5PZIrhBnIaRTQRjqdJSsIKkOP6OAIFbj7GOrcudc5pNjZ+geV2g==";
      };
    };
    "postcss-8.4.38" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.38";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.38.tgz";
        sha512 = "Wglpdk03BSfXkHoQa3b/oulrotAkwrlLDRSOb9D0bN86FdRyE9lppSp33aHNPgBa0JKCoB+drFLZkQoRRYae5A==";
      };
    };
    "postcss-load-config-5.0.3" = {
      name = "postcss-load-config";
      packageName = "postcss-load-config";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-load-config/-/postcss-load-config-5.0.3.tgz";
        sha512 = "90pBBI5apUVruIEdCxZic93Wm+i9fTrp7TXbgdUCH+/L+2WnfpITSpq5dFU/IPvbv7aNiMlQISpUkAm3fEcvgQ==";
      };
    };
    "prettier-3.2.5" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.2.5.tgz";
        sha512 = "3/GWa9aOC0YeD7LUfvOG2NiDyhOWRvt1k+rcKhOuYnMY24iiCphgneUfJDyFXd6rZCAnuLBv6UeAULtrhT/F4A==";
      };
    };
    "prettier-plugin-svelte-3.2.3" = {
      name = "prettier-plugin-svelte";
      packageName = "prettier-plugin-svelte";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-3.2.3.tgz";
        sha512 = "wJq8RunyFlWco6U0WJV5wNCM7zpBFakS76UBSbmzMGpncpK98NZABaE+s7n8/APDCEVNHXC5Mpq+MLebQtsRlg==";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "nolQXZ/4L+bP/UGlkfaIujX9BKxGwmQ9OT4mOt5yvy8iK1h3wqTEJCijzGANTCCl9nWjY41juyAn2K3Q1hLLTg==";
      };
    };
    "prr-1.0.1" = {
      name = "prr";
      packageName = "prr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-1.0.1.tgz";
        sha512 = "yPw4Sng1gWghHQWj0B3ZggWUm4qVbPwPFcRG8KyxiU7J2OHFSoEHKS+EZ3fv5l1t9CyCiop6l/ZYeWbrgoQejw==";
      };
    };
    "pug-3.0.2" = {
      name = "pug";
      packageName = "pug";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug/-/pug-3.0.2.tgz";
        sha512 = "bp0I/hiK1D1vChHh6EfDxtndHji55XP/ZJKwsRqrz6lRia6ZC2OZbdAymlxdVFwd1L70ebrVJw4/eZ79skrIaw==";
      };
    };
    "pug-attrs-3.0.0" = {
      name = "pug-attrs";
      packageName = "pug-attrs";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-attrs/-/pug-attrs-3.0.0.tgz";
        sha512 = "azINV9dUtzPMFQktvTXciNAfAuVh/L/JCl0vtPCwvOA21uZrC08K/UnmrL+SXGEVc1FwzjW62+xw5S/uaLj6cA==";
      };
    };
    "pug-code-gen-3.0.2" = {
      name = "pug-code-gen";
      packageName = "pug-code-gen";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-code-gen/-/pug-code-gen-3.0.2.tgz";
        sha512 = "nJMhW16MbiGRiyR4miDTQMRWDgKplnHyeLvioEJYbk1RsPI3FuA3saEP8uwnTb2nTJEKBU90NFVWJBk4OU5qyg==";
      };
    };
    "pug-error-2.0.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.0.0.tgz";
        sha512 = "sjiUsi9M4RAGHktC1drQfCr5C5eriu24Lfbt4s+7SykztEOwVZtbFk1RRq0tzLxcMxMYTBR+zMQaG07J/btayQ==";
      };
    };
    "pug-filters-4.0.0" = {
      name = "pug-filters";
      packageName = "pug-filters";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-filters/-/pug-filters-4.0.0.tgz";
        sha512 = "yeNFtq5Yxmfz0f9z2rMXGw/8/4i1cCFecw/Q7+D0V2DdtII5UvqE12VaZ2AY7ri6o5RNXiweGH79OCq+2RQU4A==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "pug-linker-4.0.0" = {
      name = "pug-linker";
      packageName = "pug-linker";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-linker/-/pug-linker-4.0.0.tgz";
        sha512 = "gjD1yzp0yxbQqnzBAdlhbgoJL5qIFJw78juN1NpTLt/mfPJ5VgC4BvkoD3G23qKzJtIIXBbcCt6FioLSFLOHdw==";
      };
    };
    "pug-load-3.0.0" = {
      name = "pug-load";
      packageName = "pug-load";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-load/-/pug-load-3.0.0.tgz";
        sha512 = "OCjTEnhLWZBvS4zni/WUMjH2YSUosnsmjGBB1An7CsKQarYSWQ0GCVyd4eQPMFJqZ8w9xgs01QdiZXKVjk92EQ==";
      };
    };
    "pug-parser-6.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz";
        sha512 = "ukiYM/9cH6Cml+AOl5kETtM9NR3WulyVP2y4HOU45DyMim1IeP/OOiyEWRr6qk5I5klpsBnbuHpwKmTx6WURnw==";
      };
    };
    "pug-runtime-3.0.1" = {
      name = "pug-runtime";
      packageName = "pug-runtime";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-runtime/-/pug-runtime-3.0.1.tgz";
        sha512 = "L50zbvrQ35TkpHwv0G6aLSuueDRwc/97XdY8kL3tOT0FmhgG7UypU3VztfV/LATAvmUfYi4wNxSajhSAeNN+Kg==";
      };
    };
    "pug-strip-comments-2.0.0" = {
      name = "pug-strip-comments";
      packageName = "pug-strip-comments";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-strip-comments/-/pug-strip-comments-2.0.0.tgz";
        sha512 = "zo8DsDpH7eTkPHCXFeAk1xZXJbyoTfdPlNR0bK7rpOMuhBYb0f5qUVCO1xlsitYd3w5FQTK7zpNVKb3rZoUrrQ==";
      };
    };
    "pug-walk-2.0.0" = {
      name = "pug-walk";
      packageName = "pug-walk";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-walk/-/pug-walk-2.0.0.tgz";
        sha512 = "yYELe9Q5q9IQhuvqsZNwA5hfPkMJ8u92bQLIMcsMxf/VADjNtEYptU+inlufAFYcWdHlwNfZOEnOOQrZrcyJCQ==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "resolve-1.22.8" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.8.tgz";
        sha512 = "oKWePCxqpd6FlLvGV1VU0x7bkPmmCNolxzjMf4NczoDnQcIWrAF+cPtZn5i6n+RfD2d9i0tzpKnG6Yk168yIyw==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rimraf-2.7.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz";
        sha512 = "uWjbaKIK3T1OSVptzX7Nl6PvQ3qAGtKEtVRjRuazjfL3Bx5eI409VZSqgND+4UNnmzLVdPj9FqFJNPqBZFve4w==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sander-0.5.1" = {
      name = "sander";
      packageName = "sander";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sander/-/sander-0.5.1.tgz";
        sha512 = "3lVqBir7WuKDHGrKRDn/1Ye3kwpXaDOMsiRP1wd6wpZW56gJhsbp5RqQpA6JG/P+pkXizygnr1dKR8vzWaVsfA==";
      };
    };
    "sass-1.75.0" = {
      name = "sass";
      packageName = "sass";
      version = "1.75.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.75.0.tgz";
        sha512 = "ShMYi3WkrDWxExyxSZPst4/okE9ts46xZmJDSawJQrnte7M1V9fScVB+uNXOVKRBt0PggHOwoZcn8mYX4trnBw==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "sax-1.3.0" = {
      name = "sax";
      packageName = "sax";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.3.0.tgz";
        sha512 = "0s+oAmw9zLl1V1cS9BtZN7JAd0cW5e0QH4W3LWEK6a4LaLEA2OTpGYWDY+6XasBLtz6wkm3u1xRw95mRuJ59WA==";
      };
    };
    "semver-5.7.2" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.2.tgz";
        sha512 = "cBznnQ9KjJqU67B52RMC65CMarK2600WFnbkcaiwWq3xy/5haFJlshgnpjovMVJ+Hff49d8GEn0b87C5pDQ10g==";
      };
    };
    "semver-6.3.1" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.1.tgz";
        sha512 = "BR7VvDCVHO+q2xBEWskxS6DJE1qRnb7DxzUrogb71CWoSficBxYsiAGd+Kl0mmq/MprG9yArRkyrQxTO6XjMzA==";
      };
    };
    "semver-7.6.0" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.0.tgz";
        sha512 = "EnwXhrlwXMk9gKu5/flx5sv/an57AkRplG3hTK68W7FRDN+k+OWBj65M7719OkA82XLBxrcX0KSHj+X5COhOVg==";
      };
    };
    "set-function-length-1.2.2" = {
      name = "set-function-length";
      packageName = "set-function-length";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-function-length/-/set-function-length-1.2.2.tgz";
        sha512 = "pgRc4hJ4/sNjWCSS9AmnS40x3bNMDTknHgL5UaMBTMyJnU90EgWh1Rz+MC9eFu4BuN/UwZjKQuY/1v3rM7HMfg==";
      };
    };
    "sorcery-0.11.0" = {
      name = "sorcery";
      packageName = "sorcery";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sorcery/-/sorcery-0.11.0.tgz";
        sha512 = "J69LQ22xrQB1cIFJhPfgtLuI6BpWRiWu1Y3vSsIwK/eAScqJxd/+CJlUuHQRdX2C9NGFamq+KqNywGgaThwfHw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.7.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.7.4.tgz";
        sha512 = "l3BikUxvPOcn5E74dZiq5BGsTb5yEwhaTSzccU6t4sDOH8NWJCstKO5QT2CvtFoK6F0saL7p9xHAqHOlCPJygA==";
      };
    };
    "source-map-js-1.2.0" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.0.tgz";
        sha512 = "itJW8lvSA0TXEphiRoawsCksnlf8SyvmFzIhltqAHluXd88pkCd+cXJVHTDwdCr0IzwptSm035IHQktUu1QUMg==";
      };
    };
    "source-map-resolve-0.6.0" = {
      name = "source-map-resolve";
      packageName = "source-map-resolve";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-resolve/-/source-map-resolve-0.6.0.tgz";
        sha512 = "KXBr9d/fO/bWo97NXsPIAW1bFSBOuCnjbNTBMO7N59hsv5i9yzRDfcYwwt0l04+VqnKC+EwzvJZIP/qkuMgR/w==";
      };
    };
    "strip-indent-3.0.0" = {
      name = "strip-indent";
      packageName = "strip-indent";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-indent/-/strip-indent-3.0.0.tgz";
        sha512 = "laJTa3Jb+VQpaC6DseHhF7dXVqHTfJPCRDaEbid/drOhgitgYku/letMUqOXFoWV0zIIUbjpdH2t+tYj4bQMRQ==";
      };
    };
    "stylus-0.55.0" = {
      name = "stylus";
      packageName = "stylus";
      version = "0.55.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylus/-/stylus-0.55.0.tgz";
        sha512 = "MuzIIVRSbc8XxHH7FjkvWqkIcr1BvoMZoR/oFuAJDlh7VSaNJzrB4uJ38GRQa+mWjLXODAMzeDe0xi9GYbGwnw==";
      };
    };
    "sugarss-4.0.1" = {
      name = "sugarss";
      packageName = "sugarss";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sugarss/-/sugarss-4.0.1.tgz";
        sha512 = "WCjS5NfuVJjkQzK10s8WOBY+hhDxxNt/N6ZaGwxFZ+wN3/lKKFSaaKUNecULcTTvE4urLcKaZFQD8vO0mOZujw==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "svelte-3.59.2" = {
      name = "svelte";
      packageName = "svelte";
      version = "3.59.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-3.59.2.tgz";
        sha512 = "vzSyuGr3eEoAtT/A6bmajosJZIUWySzY2CzB3w2pgPvnkUjGqlDnsNnA0PMO+mMAhuyMul6C2uuZzY6ELSkzyA==";
      };
    };
    "svelte-preprocess-5.1.4" = {
      name = "svelte-preprocess";
      packageName = "svelte-preprocess";
      version = "5.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte-preprocess/-/svelte-preprocess-5.1.4.tgz";
        sha512 = "IvnbQ6D6Ao3Gg6ftiM5tdbR6aAETwjhHV+UKGf5bHGYR69RQvF1ho0JKPcbUON4vy4R7zom13jPjgdOWCQ5hDA==";
      };
    };
    "svelte2tsx-0.7.7" = {
      name = "svelte2tsx";
      packageName = "svelte2tsx";
      version = "0.7.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte2tsx/-/svelte2tsx-0.7.7.tgz";
        sha512 = "HAIxtk5TUHXvCRKApKfxoh1BGT85S/17lS3DvbfxRKFd+Ghr5YScqBvd+sU+p7vJFw48LNkzdFk+ooNVk3e4kA==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha512 = "/OaKK0xYrs3DmxRYqL/yDc+FxFUVYhDlXMhRmv3z915w2HF1tnN1omB354j8VUGO/hbRzyD6Y3sA7v7GS/ceog==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "token-stream-1.0.0" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz";
        sha512 = "VSsyNPPW74RpHwR8Fc21uubwHY7wMDeJLys2IX5zJNih+OnAnaifKHo+1LHT7DAdloQ7apeaaWg8l7qnf/TnEg==";
      };
    };
    "tslib-2.6.2" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.6.2.tgz";
        sha512 = "AEYxH93jGFPn/a2iVAwW87VuUIkR1FVUKB77NwMF7nBTDkDrrT/Hpt/IrCJ0QXhW27jTBDcf5ZY7w6RiqTMw2Q==";
      };
    };
    "typescript-5.4.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.4.5.tgz";
        sha512 = "vcI4UpRgg81oIRUFwR0WSIHKt11nJ7SAVlYNIu+QpqeyXP+gpQJy/Z4+F0aGxSE4MqwjyXvW/TzgkLAx2AGHwQ==";
      };
    };
    "typescript-auto-import-cache-0.3.2" = {
      name = "typescript-auto-import-cache";
      packageName = "typescript-auto-import-cache";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-auto-import-cache/-/typescript-auto-import-cache-0.3.2.tgz";
        sha512 = "+laqe5SFL1vN62FPOOJSUDTZxtgsoOXjneYOXIpx5rQ4UMiN89NAtJLpqLqyebv9fgQ/IMeeTX+mQyRnwvJzvg==";
      };
    };
    "update-browserslist-db-1.0.13" = {
      name = "update-browserslist-db";
      packageName = "update-browserslist-db";
      version = "1.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-browserslist-db/-/update-browserslist-db-1.0.13.tgz";
        sha512 = "xebP81SNcPuNpPP3uzeW1NYXxI3rxyJzF3pD6sH4jE7o/IX+WtSpwnVU+qIsDPyk0d3hmFQ7mjqc6AtV604hbg==";
      };
    };
    "void-elements-3.1.0" = {
      name = "void-elements";
      packageName = "void-elements";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/void-elements/-/void-elements-3.1.0.tgz";
        sha512 = "Dhxzh5HZuiHQhbvTW9AMetFfBHDMYpo23Uo9btPXgdYP+3T5S+p+jgNy7spra+veYhBP2dCSgxR/i2Y02h5/6w==";
      };
    };
    "vscode-css-languageservice-6.2.14" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "6.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.2.14.tgz";
        sha512 = "5UPQ9Y1sUTnuMyaMBpO7LrBkqjhEJb5eAwdUlDp+Uez8lry+Tspnk3+3p2qWS4LlNsr4p3v9WkZxUf1ltgFpgw==";
      };
    };
    "vscode-html-languageservice-5.1.2" = {
      name = "vscode-html-languageservice";
      packageName = "vscode-html-languageservice";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.1.2.tgz";
        sha512 = "wkWfEx/IIR3s2P5yD4aTGHiOb8IAzFxgkSt1uSC3itJ4oDAm23yG7o0L29JljUdnXDDgLafPAvhv8A2I/8riHw==";
      };
    };
    "vscode-jsonrpc-8.0.2" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.0.2.tgz";
        sha512 = "RY7HwI/ydoC1Wwg4gJ3y6LpU9FJRZAUnTYMXthqhFXXu77ErDd/xkREpGuk4MyYkk4a+XDWAMqe0S3KkelYQEQ==";
      };
    };
    "vscode-languageserver-8.0.2" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.0.2.tgz";
        sha512 = "bpEt2ggPxKzsAOZlXmCJ50bV7VrxwCS5BI4+egUmure/oI/t4OlFzi/YNtVvY24A2UDOZAgwFGgnZPwqSJubkA==";
      };
    };
    "vscode-languageserver-protocol-3.17.2" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.2.tgz";
        sha512 = "8kYisQ3z/SQ2kyjlNeQxbkkTNmVFoQCqkmGrzLH6A9ecPlgTbp3wDTnUNqaUxYr4vlAcloxx8zwy7G5WdguYNg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.11" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.11.tgz";
        sha512 = "X+8T3GoiwTVlJbicx/sIAF+yuJAqz8VvwJyoMVhwEMoEKE/fkDmrqUgDMyBECcM2A2frVZIUj5HI/ErRXCfOeA==";
      };
    };
    "vscode-languageserver-types-3.17.2" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.2.tgz";
        sha512 = "zHhCWatviizPIq9B7Vh9uvrH6x3sK8itC84HkamnBWoDFJtzBf7SWlpLCZUit72b3os45h6RWQNC9xHRDF8dRA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-nls-5.2.0" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.2.0.tgz";
        sha512 = "RAaHx7B14ZU04EU31pT+rKz2/zSl7xMsfIZuo8pd+KZO6PXtQmpevpq3vxvWNcrGbdmhM/rr5Uw5Mz+NBfhVng==";
      };
    };
    "vscode-uri-2.1.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.1.2.tgz";
        sha512 = "8TEXQxlldWAuIODdukIb+TR5s+9Ds40eSJrw+1iDDA9IFORPjMELarNQE3myz5XIkWWpdprmJjm1/SxMlWOC8A==";
      };
    };
    "vscode-uri-3.0.8" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.8.tgz";
        sha512 = "AyFQ0EVmsOZOlAnxoFOGOq1SQDWAB7C6aqMGS23svWAllfOaxbuFvcT8D1i8z3Gyn8fraVeZNNmN6e9bxxXkKw==";
      };
    };
    "with-7.0.2" = {
      name = "with";
      packageName = "with";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/with/-/with-7.0.2.tgz";
        sha512 = "RNGKj82nUPg3g5ygxkQl0R937xLyho1J24ItRCBTr/m1YnZkzJy1hUiHUJrc/VlsDQzsCnInEGSg3bci0Lmd4w==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yallist-3.1.1" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz";
        sha512 = "a4UGQaWPH59mOXUYnAG2ewncQS4i4F43Tv3JoAM+s2VDAmS9NsK8GpDMLrCHPksFT7h3K6TOoUNn2pb7RoXx4g==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yaml-2.4.1" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.4.1.tgz";
        sha512 = "pIXzoImaqmfOrL7teGUBt/T7ZDnyeGBWyXQBvOVhLkWLN37GXv8NMLK406UY6dS51JfcQHsmcW5cJ441bHg6Lg==";
      };
    };
  };
in
{
  svelte-language-server = nodeEnv.buildNodePackage {
    name = "svelte-language-server";
    packageName = "svelte-language-server";
    version = "0.16.8";
    src = fetchurl {
      url = "https://registry.npmjs.org/svelte-language-server/-/svelte-language-server-0.16.8.tgz";
      sha512 = "gGtWwQStHrVnQrMQGgUPVw7djoR1ezXW2oWSZwR7BdCD/9QVse7BY6+WlNKO4oqu5FqbfOCq/hWKqMlkXkSvwQ==";
    };
    dependencies = [
      sources."@ampproject/remapping-2.3.0"
      sources."@babel/code-frame-7.24.2"
      sources."@babel/compat-data-7.24.4"
      sources."@babel/core-7.24.4"
      sources."@babel/generator-7.24.4"
      sources."@babel/helper-compilation-targets-7.23.6"
      sources."@babel/helper-environment-visitor-7.22.20"
      sources."@babel/helper-function-name-7.23.0"
      sources."@babel/helper-hoist-variables-7.22.5"
      sources."@babel/helper-module-imports-7.24.3"
      sources."@babel/helper-module-transforms-7.23.3"
      sources."@babel/helper-simple-access-7.22.5"
      sources."@babel/helper-split-export-declaration-7.22.6"
      sources."@babel/helper-string-parser-7.24.1"
      sources."@babel/helper-validator-identifier-7.22.20"
      sources."@babel/helper-validator-option-7.23.5"
      sources."@babel/helpers-7.24.4"
      sources."@babel/highlight-7.24.2"
      sources."@babel/parser-7.24.4"
      sources."@babel/template-7.24.0"
      sources."@babel/traverse-7.24.1"
      sources."@babel/types-7.24.0"
      sources."@emmetio/abbreviation-2.3.3"
      sources."@emmetio/css-abbreviation-2.1.8"
      sources."@emmetio/scanner-1.0.4"
      sources."@jridgewell/gen-mapping-0.3.5"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/set-array-1.2.1"
      sources."@jridgewell/sourcemap-codec-1.4.15"
      sources."@jridgewell/trace-mapping-0.3.25"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@types/pug-2.0.10"
      (sources."@vscode/emmet-helper-2.8.4" // {
        dependencies = [
          sources."vscode-uri-2.1.2"
        ];
      })
      sources."@vscode/l10n-0.0.18"
      sources."acorn-7.4.1"
      sources."ansi-styles-3.2.1"
      sources."anymatch-3.1.3"
      sources."asap-2.0.6"
      sources."assert-never-1.2.1"
      sources."atob-2.1.2"
      sources."babel-walk-3.0.0-canary-5"
      sources."balanced-match-1.0.2"
      sources."binary-extensions-2.3.0"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."browserslist-4.23.0"
      sources."buffer-crc32-0.2.13"
      sources."call-bind-1.0.7"
      sources."caniuse-lite-1.0.30001613"
      sources."chalk-2.4.2"
      sources."character-parser-2.2.0"
      sources."chokidar-3.6.0"
      sources."coffeescript-2.7.0"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."constantinople-4.0.1"
      sources."convert-source-map-2.0.0"
      sources."copy-anything-2.0.6"
      sources."css-3.0.0"
      sources."debug-4.3.4"
      sources."decode-uri-component-0.2.2"
      sources."dedent-js-1.0.1"
      sources."define-data-property-1.1.4"
      sources."detect-indent-6.1.0"
      sources."doctypes-1.1.0"
      sources."electron-to-chromium-1.4.750"
      sources."emmet-2.4.7"
      sources."errno-0.1.8"
      sources."es-define-property-1.0.0"
      sources."es-errors-1.3.0"
      sources."es6-promise-3.3.1"
      sources."escalade-3.1.2"
      sources."escape-string-regexp-1.0.5"
      sources."estree-walker-2.0.2"
      sources."fast-glob-3.3.2"
      sources."fastq-1.17.1"
      sources."fill-range-7.0.1"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.2"
      sources."gensync-1.0.0-beta.2"
      sources."get-intrinsic-1.2.4"
      sources."glob-7.2.3"
      sources."glob-parent-5.1.2"
      sources."globals-11.12.0"
      sources."gopd-1.0.1"
      sources."graceful-fs-4.2.11"
      sources."has-flag-3.0.0"
      sources."has-property-descriptors-1.0.2"
      sources."has-proto-1.0.3"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."iconv-lite-0.6.3"
      sources."image-size-0.5.5"
      sources."immutable-4.3.5"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-binary-path-2.1.0"
      sources."is-core-module-2.13.1"
      sources."is-expression-4.0.0"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."is-promise-2.2.2"
      sources."is-regex-1.1.4"
      sources."is-what-3.14.1"
      sources."jiti-1.21.0"
      sources."js-stringify-1.0.2"
      sources."js-tokens-4.0.0"
      sources."jsesc-2.5.2"
      sources."json5-2.2.3"
      sources."jsonc-parser-2.3.1"
      sources."jstransformer-1.0.0"
      sources."less-4.2.0"
      sources."lilconfig-3.1.1"
      sources."lodash-4.17.21"
      sources."lower-case-2.0.2"
      sources."lru-cache-5.1.1"
      sources."magic-string-0.30.10"
      (sources."make-dir-2.1.0" // {
        dependencies = [
          sources."semver-5.7.2"
        ];
      })
      sources."merge2-1.4.1"
      sources."micromatch-4.0.5"
      sources."mime-1.6.0"
      sources."min-indent-1.0.1"
      sources."minimatch-3.1.2"
      sources."minimist-1.2.8"
      sources."mkdirp-0.5.6"
      sources."ms-2.1.2"
      sources."nanoid-3.3.7"
      sources."needle-3.3.1"
      sources."no-case-3.0.4"
      sources."node-releases-2.0.14"
      sources."normalize-path-3.0.0"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."parse-node-version-1.0.1"
      sources."pascal-case-3.1.2"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.7"
      sources."picocolors-1.0.0"
      sources."picomatch-2.3.1"
      sources."pify-4.0.1"
      sources."postcss-8.4.38"
      sources."postcss-load-config-5.0.3"
      sources."prettier-3.2.5"
      sources."prettier-plugin-svelte-3.2.3"
      sources."promise-7.3.1"
      sources."prr-1.0.1"
      sources."pug-3.0.2"
      sources."pug-attrs-3.0.0"
      sources."pug-code-gen-3.0.2"
      sources."pug-error-2.0.0"
      sources."pug-filters-4.0.0"
      sources."pug-lexer-5.0.1"
      sources."pug-linker-4.0.0"
      sources."pug-load-3.0.0"
      sources."pug-parser-6.0.0"
      sources."pug-runtime-3.0.1"
      sources."pug-strip-comments-2.0.0"
      sources."pug-walk-2.0.0"
      sources."queue-microtask-1.2.3"
      sources."readdirp-3.6.0"
      sources."resolve-1.22.8"
      sources."reusify-1.0.4"
      sources."rimraf-2.7.1"
      sources."run-parallel-1.2.0"
      sources."safer-buffer-2.1.2"
      sources."sander-0.5.1"
      sources."sass-1.75.0"
      sources."sax-1.3.0"
      sources."semver-6.3.1"
      sources."set-function-length-1.2.2"
      sources."sorcery-0.11.0"
      sources."source-map-0.6.1"
      sources."source-map-js-1.2.0"
      sources."source-map-resolve-0.6.0"
      sources."strip-indent-3.0.0"
      (sources."stylus-0.55.0" // {
        dependencies = [
          sources."debug-3.1.0"
          sources."mkdirp-1.0.4"
          sources."ms-2.0.0"
          sources."sax-1.2.4"
          sources."source-map-0.7.4"
        ];
      })
      sources."sugarss-4.0.1"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."svelte-3.59.2"
      sources."svelte-preprocess-5.1.4"
      sources."svelte2tsx-0.7.7"
      sources."to-fast-properties-2.0.0"
      sources."to-regex-range-5.0.1"
      sources."token-stream-1.0.0"
      sources."tslib-2.6.2"
      sources."typescript-5.4.5"
      (sources."typescript-auto-import-cache-0.3.2" // {
        dependencies = [
          sources."lru-cache-6.0.0"
          sources."semver-7.6.0"
          sources."yallist-4.0.0"
        ];
      })
      sources."update-browserslist-db-1.0.13"
      sources."void-elements-3.1.0"
      (sources."vscode-css-languageservice-6.2.14" // {
        dependencies = [
          sources."vscode-languageserver-types-3.17.5"
        ];
      })
      (sources."vscode-html-languageservice-5.1.2" // {
        dependencies = [
          sources."vscode-languageserver-types-3.17.5"
        ];
      })
      sources."vscode-jsonrpc-8.0.2"
      sources."vscode-languageserver-8.0.2"
      sources."vscode-languageserver-protocol-3.17.2"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.17.2"
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.0.8"
      sources."with-7.0.2"
      sources."wrappy-1.0.2"
      sources."yallist-3.1.1"
      sources."yaml-2.4.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A language server for Svelte";
      homepage = "https://github.com/sveltejs/language-tools#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}

