version: '3.7'
services:
  server:
    image: vectorim/element-web
    networks:
      - caddy
    labels:
      caddy: matrix.nkit.dev
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
