{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.kit.mutableConfig;

  fileType = lib.types.submodule (
    { name, ... }:
    {
      options = {
        strategy = lib.mkOption {
          type = lib.types.enum [
            "strict"
            "merge"
            "trackOnly"
          ];
          default = "strict";
          description = ''
            How to handle a writable target. `strict` refuses to replace user
            changes, `merge` combines JSON objects (see `mergePriority`), and
            `trackOnly` only includes an explicitly generated source in
            `kit config diff`.

            The merging / equality strategies can be extended later if the
            current approaches give too many false-positive diffs — for
            example ignoring newlines, or for multiple languages treating
            soft-copy as in-sync when formatting both sides yields the same
            content.
          '';
        };

        mergePriority = lib.mkOption {
          type = lib.types.enum [
            "nix"
            "live"
          ];
          default = "nix";
          description = ''
            Only used when `strategy = "merge"`. `nix` means Home Manager
            values win on key conflicts (`live * nix`); `live` means the
            on-disk file wins (`nix * live`), while still filling in keys
            that exist only in Nix.
          '';
        };

        mergeFormat = lib.mkOption {
          type = lib.types.enum [
            "json"
            "json5"
          ];
          default = "json5";
          description = "Parser used for the live side of JSON merges and diffs.";
        };

        source = lib.mkOption {
          type = lib.types.nullOr lib.types.path;
          default = null;
          description = ''
            Explicit desired source. Normally this is inferred from the
            matching final `home.file` entry generated by Home Manager.
            `trackOnly` requires an explicit source because it does not take
            ownership away from Home Manager.
          '';
        };
      };
    }
  );

  xdgRoots = [
    config.xdg.cacheHome
    config.xdg.configHome
    config.xdg.dataHome
    config.xdg.stateHome
  ];

  targetFor = name: "${config.home.homeDirectory}/${name}";

  # XDG file options are lowered into home.file with an absolute attribute
  # name. Direct home.file declarations conventionally retain their
  # home-relative attribute name.
  homeFileKeyFor =
    name:
    let
      target = targetFor name;
      isXdgTarget = lib.any (root: lib.hasPrefix "${toString root}/" target) xdgRoots;
    in
    if isXdgTarget then target else name;

  sourceFor =
    name: file:
    if file.source != null then file.source else config.home.file.${homeFileKeyFor name}.source;

  # A bare `./file.nix`-style source carries no string context, so recording it
  # in the manifest would leave the activation script with no reference to it
  # and the path can vanish before activation runs. Give those their own store
  # path, the same way Home Manager's files module does.
  storePathFor =
    name: file:
    let
      source = sourceFor name file;
    in
    if builtins.hasContext (toString source) then
      source
    else
      builtins.path {
        path = source;
        name = lib.hm.strings.storeFileName (baseNameOf (toString source));
      };

  manifestEntries = lib.mapAttrsToList (name: file: {
    inherit name;
    id = builtins.substring 0 20 (builtins.hashString "sha256" name);
    target = targetFor name;
    source = "${storePathFor name file}";
    inherit (file) strategy mergeFormat mergePriority;
  }) cfg.files;

  ownedFiles = lib.filterAttrs (_: file: file.strategy != "trackOnly") cfg.files;
in
{
  options.kit.mutableConfig = {
    files = lib.mkOption {
      type = lib.types.attrsOf fileType;
      default = { };
      description = ''
        Writable files generated from Home Manager configuration. Attribute
        names are paths relative to the user's home directory.
      '';
    };

    manifest = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      internal = true;
      description = "JSON manifest consumed by `kit config`.";
    };
  };

  config = {
    kit.mutableConfig.manifest = pkgs.writeText "kit-mutable-config-manifest.json" (
      builtins.toJSON manifestEntries
    );

    assertions = lib.mapAttrsToList (name: file: {
      assertion =
        !lib.hasPrefix "/" name
        && name != ""
        && !(lib.elem ".." (lib.splitString "/" name))
        && (file.strategy != "trackOnly" || file.source != null);
      message = ''
        kit.mutableConfig.files.${name}: paths must be non-empty and
        home-relative without `..`; trackOnly entries also require `source`.
      '';
    }) cfg.files;

    # Keep the program-specific Home Manager module as the generator, but
    # prevent its final home.file entry from becoming a Nix-store symlink.
    home.file = lib.mkIf (ownedFiles != { }) (
      lib.mapAttrs' (
        name: file:
        lib.nameValuePair (homeFileKeyFor name) (
          {
            enable = lib.mkForce false;
          }
          // lib.optionalAttrs (file.source != null) {
            inherit (file) source;
          }
        )
      ) ownedFiles
    );
  };
}
