version: '3.7'
services:
  server:
    image: ghcr.io/open-webui/open-webui:latest
    networks:
      - caddy
    labels:
      caddy: ow.nkit.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"
    volumes:
      - open_webui:/app/backend/data


networks:
  caddy:
    external: true

volumes:
  open_webui:

