version: '3.7'
services:
  server:
    image: p3terx/ariang
    networks:
      - caddy
    labels:
      caddy: aria2.nkit.dev
      caddy.reverse_proxy: "{{upstreams 6880}}"

networks:
  caddy:
    external: true
