apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-full-access
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only-everywhere
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-full-access-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: default
roleRef:
  kind: Role
  name: default-full-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-only-everywhere-binding
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: default
roleRef:
  kind: ClusterRole
  name: read-only-everywhere
  apiGroup: rbac.authorization.k8s.io
---

